<?xml version="1.0" encoding="utf-8"?><Database Name="SecurityDB" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-HV3QCDOK\SQLEXPRESS;Initial Catalog=SecurityDB;Integrated Security=True" SettingsObjectName="Automated_workstation_of_the_personnel_department.Properties.Settings" SettingsPropertyName="SecurityDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.User_tbl" Member="User_tbl">
    <Type Name="User_tbl">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
</Database>